language: c
compiler:
  - clang
  - gcc
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

sudo: false

addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - ninja-build

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja ..
  - ninja
