language: c

# Configure environment
sudo: false
addons:
  apt:
    sources:
      # Needed for newer CMake
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - ninja-build
      - perl # For tests
      - python3 # For tests
      - lcov # For coverage

# Set up build matrix
compiler:
  - clang
  - gcc
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

script:
  - mkdir build && cd build
  # Only build coverage for one variant
  - |
    if [[ $CC == gcc && $BUILD_TYPE == Debug ]]; then
      touch "${TRAVIS_BUILD_DIR}/.coverage_generated"
      EXTRA_FLAGS="-DCFUNGE_ENABLE_COVERAGE:BOOL=ON"
    fi
    cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE CFLAGS="$EXTRA_CFLAGS" $EXTRA_FLAGS -G Ninja ..
    ninja
    # For debugging purposes show details of cfunge:
    ./cfunge -v
    ./cfunge -f
    ctest --output-on-failure
    if [[ $? -eq 0 && -f "${TRAVIS_BUILD_DIR}/.coverage_generated" ]]; then
      ninja cfunge_coverage
    fi

after_success:
  - |
    if [[ -f "${TRAVIS_BUILD_DIR}/.coverage_generated" ]]; then
      lcov --directory . --capture --output-file coverage.info # capture coverage info
      lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
      lcov --list coverage.info #debug info
      bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    fi
