language: c

# Configure environment
sudo: false
addons:
  apt:
    sources:
      # Needed for newer CMake
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - ninja-build

# Set up build matrix
compiler:
  - clang
  - gcc
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja ..
  - ninja
